// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace unity_ecs_summarizer
{
    internal sealed partial class Vsix
    {
        public const string Id = "unity_ecs_summarizer.4d5ab4aa-cebc-4b86-9793-91242b983e76";
        public const string Name = "Unity ECS Summarizer";
        public const string Description = @"Creates EntityQuery and ComponentSet summaries that contain components in the query or script.C";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Lar Kunc";
        public const string Tags = "";
    }
}
