// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace unity_ecs_summarizer
{
    internal sealed partial class Vsix
    {
        public const string Id = "unity_ecs_summarizer.4d5ab4aa-cebc-4b86-9793-91242b983e76";
        public const string Name = "Unity ECS Summarizer";
        public const string Description = @"Creates EntityQuery and ComponentTypeSet summaries of the components in the query or the set.";
        public const string Language = "en-US";
        public const string Version = "1.2";
        public const string Author = "larchman01";
        public const string Tags = "unity ecs, unity dots, c#, summary, summarizer, unity, unity3d, ecs, dots";
    }
}
