// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace unity_ecs_summarizer
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string unity_ecs_summarizerString = "3a8d2599-38d9-43ec-961c-4deca52bf2df";
        public static Guid unity_ecs_summarizer = new Guid(unity_ecs_summarizerString);

        public const string guidSHLMainMenuString = "d309f791-903f-11d0-9efc-00a0c911004f";
        public static Guid guidSHLMainMenu = new Guid(guidSHLMainMenuString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int EcsSummarizerMenuGroup = 0x0001;
        public const int EcsSummarizerSubMenuGroup = 0x0002;
        public const int EcsSummarizerMenu = 0x0100;
        public const int SummarizeEntityQueries = 0x0101;
        public const int SummarizeComponentTypeSets = 0x0110;
        public const int IDM_VS_CTXT_CODEWIN = 0x040D;
    }
}